### ISSUE TITLE
can I delete the project on Docker hub?

### ISSUE THREAD

**Issue by targos** [cheminfo-py/xrd-tools#40]
I am doing a Docker hub cleanup and migrating active projets to [ghcr.io](https://github.blog/2021-06-21-github-packages-container-registry-generally-available/).

I see that this project is already published on GitHub for its last versions. Can I therefore delete https://hub.docker.com/r/cheminfo/xrd-tools ?

**Comment by kjappelbaum** [comment]
yes, thanks!

**Comment by targos** [comment]
done 👍🏻
